name: basismixer

channels:
  - defaults
  - pytorch

dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pytorch
  - sphinx
  - pip
  - tqdm

  - pip:
    - partitura
    