name: basismixer

channels:
  - defaults
  - speleo3
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - mkl
  - numpy
  - scipy
  - cython
  - matplotlib
  - ipython
  - jupyter
  - pandas
  - sympy
  - nose
  - autopep8
  - virtualenv
  - pytorch
  - torchvision
  - scikit-learn
  - sphinx
  - pip

  - pip:
    - madmom
    - jedi
    - lark-parser
