name: basismixer

channels:
  - defaults
  - pytorch
  - nvidia

dependencies:
  - nvidia::cudatoolkit=11.3
  - python=3.7
  - pytorch::pytorch
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pip
  - tqdm

  - pip:
    - appdirs
    - soundfile
#    - git+https://github.com/OFAI/partitura.git@develop
#    - git+https://github.com/OFAI/basismixer.git@develop
