name: basismixer

channels:
  - defaults
  - pytorch

dependencies:
  - python=3.7
  - pytorch
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pip
  - tqdm

  - pip:
    - appdirs
    - soundfile
    - git+https://github.com/OFAI/partitura.git@main
    - git+https://github.com/OFAI/basismixer.git@asap
